version: "3"

services:
  client-service:
    image: darkandy/ado-client-msvc
    container_name: client-service
    ports:
      - "3001:3001"
    networks:
      - my_network

  category-service:
    image: darkandy/ado-category-msvc
    container_name: category-service
    ports:
      - "3002:3000"
    networks:
      - my_network

  product-service:
    image: darkandy/ado-product-msvc
    container_name: product-service
    ports:
      - "3003:3000"
    networks:
      - my_network

networks:
  my_network:
    driver: bridge
